network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: no
      addresses: [old_ip/24]
      routes:
        - to: default
          via: old_route
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
